### ISSUE TITLE
Match templates on PC/server (node js) with GT5XX FPM module?

### ISSUE THREAD

**Issue by baha0304** [brianrho/GT5X#1]
How I can create this script ? Please Help me? it is Possible?

**Comment by brianrho** [comment]
What is the exact name of your module?

**Comment by baha0304** [comment]
GT521F32 https://www.sparkfun.com/products/14518

**Comment by brianrho** [comment]
There's no way at the moment to match templates outside the module. It was possible for the FPM10 and the rest of that family because I happened to find a DLL for it and even then that only works on Windows. The GT5X sensors belong to a different family with different commands and behaviour. You can try contacting the manufacturer for help, and see if they can provide you with an SDK, shared library etc. that lets you match on your PC.
